[package]
name = "bearmark-macro"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = [] }

[dev-dependencies]
syn = { version = "2.0", features = ["extra-traits"] }
