[package]
name = "bearmark-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.79", features = [] }

[dev-dependencies]
syn = { version = "2.0.79", features = ["extra-traits"] }
